# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIwmFBUoxzoPgMtplnPJEntApNoRnO04
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install --quiet nltk sacremoses pandas regex mock transformers>=4.33.2 mosestokenizer bitsandbytes scipy accelerate datasets sentencepiece sacrebleu
# !python3 -c "import nltk; nltk.download('punkt')"
#

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !git clone https://github.com/AI4Bharat/IndicTrans2.git
# !git clone https://github.com/VarunGumma/IndicTransToolkit.git
# 
# %cd /content/IndicTrans2/huggingface_interface
# !python3 -m pip install --quiet -e .
# 
# %cd /content/IndicTransToolkit
# !python3 -m pip install --quiet -e .
#

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, BitsAndBytesConfig
import torch

def initialize_model_and_tokenizer(ckpt_dir, quantization=None):
    if quantization == "4-bit":
        qconfig = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
        )
    elif quantization == "8-bit":
        qconfig = BitsAndBytesConfig(
            load_in_8bit=True,
            bnb_8bit_use_double_quant=True,
            bnb_8bit_compute_dtype=torch.bfloat16,
        )
    else:
        qconfig = None

    tokenizer = AutoTokenizer.from_pretrained(ckpt_dir, trust_remote_code=True)
    model = AutoModelForSeq2SeqLM.from_pretrained(
        ckpt_dir,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        quantization_config=qconfig,
    )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    if qconfig is None:
        model = model.to(device)
        if device == "cuda":
            model.half()

    model.eval()
    return tokenizer, model

en_hi_ckpt_dir = "ai4bharat/indictrans2-en-indic-1B"
en_hi_tokenizer, en_hi_model = initialize_model_and_tokenizer(en_hi_ckpt_dir, quantization=None)

from IndicTransToolkit.processor import IndicProcessor
ip = IndicProcessor(inference=True)

from datasets import load_dataset

print("[INFO] Streaming IndicCorpV2 Hindi corpus...")

# Use the correct language-specific split
hin_stream = load_dataset(
    "ai4bharat/IndicCorpV2",
    split="hin_Deva",  # <--- correct split for Hindi
    streaming=True
)

# Sample some sentences safely
def sample_texts_safe(stream_iterable, n_samples=20):
    samples = []
    for idx, item in enumerate(stream_iterable):
        if len(samples) >= n_samples:
            break
        try:
            text = item["text"]
            if isinstance(text, bytes):
                text = text.decode("utf-8", errors="ignore")  # ignore broken bytes
            samples.append(text)
        except Exception:
            continue
    return samples

hin_samples = sample_texts_safe(hin_stream, n_samples=20)
print("Hindi samples:", hin_samples[:5])

def batch_translate_no_cache(sentences, src_lang, tgt_lang, model, tokenizer, ip):
    inputs = ip.preprocess_batch(sentences, src_lang=src_lang, tgt_lang=tgt_lang)
    model_inputs = tokenizer(
        inputs, return_tensors="pt", padding=True, truncation=True
    ).to(model.device)
    translated_tokens = model.generate(**model_inputs, use_cache=False, max_length=256)
    outputs = tokenizer.batch_decode(translated_tokens, skip_special_tokens=True)
    return ip.postprocess_batch(outputs, lang=tgt_lang)

print("[INFO] Backtranslating Hindi → English ...")
BATCH_SIZE = 16
backtranslated_eng = []

for i in range(0, len(hin_samples), BATCH_SIZE):
    batch = hin_samples[i:i+BATCH_SIZE]
    translations = batch_translate_no_cache(
        batch,
        src_lang="hin_Deva",
        tgt_lang="eng_Latn",
        model=en_hi_model,
        tokenizer=en_hi_tokenizer,
        ip=ip
    )
    backtranslated_eng.extend(translations)

print("[INFO] Sample backtranslated English sentences:")
print(backtranslated_eng[:5])

import os
output_dir = "/content/synthetic_en_hi"
os.makedirs(output_dir, exist_ok=True)

for idx, (eng, hin) in enumerate(zip(backtranslated_eng, hin_samples)):
    # Sentence-aligned file
    aligned_path = f"{output_dir}/doc{idx+1}_aligned.txt"
    with open(aligned_path, "w", encoding="utf-8") as f:
        f.write(f"ENG: {eng}\nHIN: {hin}\n")

    # Optional: Merged Hindi doc
    merged_path = f"{output_dir}/doc{idx+1}.txt"
    with open(merged_path, "w", encoding="utf-8") as f:
        f.write(hin)

print(f"[INFO] Saved synthetic parallel data at {output_dir}")

synthetic_pairs = list(zip(hin_samples, backtranslated_eng))

from datasets import Dataset

synthetic_dataset = Dataset.from_dict({
    "src": [src for src, tgt in synthetic_pairs],
    "tgt": [tgt for src, tgt in synthetic_pairs]
})

from datasets import load_dataset, Dataset, concatenate_datasets

# 1. Load Pralekha English–Hindi training split
print("[INFO] Loading Pralekha English–Hindi training data...")
pralekha = load_dataset("ai4bharat/Pralekha", "train", split="eng_hin")

# 2. Standardize column names
pralekha = pralekha.rename_columns({"src_txt": "src", "tgt_txt": "tgt"})
print("[INFO] Pralekha sample:", pralekha[:2])

# 3. Convert backtranslated pairs (Hindi → English) into dataset
print("[INFO] Building synthetic dataset from backtranslations...")
synthetic_pairs = [{"src": hi, "tgt": en} for hi, en in zip(hin_samples, backtranslated_eng)]
synthetic_ds = Dataset.from_list(synthetic_pairs)
print("[INFO] Synthetic sample:", synthetic_ds[:2])

# 4. Merge both datasets
print("[INFO] Concatenating Pralekha + Synthetic datasets...")
combined_ds = concatenate_datasets([pralekha, synthetic_ds])

# 5. Shuffle for heterogeneity
combined_ds = combined_ds.shuffle(seed=42)

print("[INFO] Combined dataset size:", len(combined_ds))
print("[INFO] Sample combined pairs:")
print(combined_ds[:5])
