# -*- coding: utf-8 -*-
"""DocumentMachineTranslation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDzM0ocxaa1UUhIckYZfBLS1WkFwxTMH
"""

!pip install -U \
  transformers \
  datasets \
  accelerate \
  peft \
  trl \
  sentencepiece

from huggingface_hub import notebook_login
notebook_login()

import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
)
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig

dataset = load_dataset("ai4bharat/pralekha", data_dir="train")

dataset = dataset.filter(
    lambda x: x["src_lang"] == "eng" and x["tgt_lang"] == "kan" and x["src_txt"] != x["tgt_txt"],
    num_proc=4,   # parallel filtering (Colab-friendly)
)
print(dataset)

def format_example(example):
    messages = {"prompt": [{"role": "user", "content": "Translate the following sentence from English to Kannada.\n\n"
                  f"English: {example['src_txt']}"}],
    "completion": [{"role": "assistant", "content": example["tgt_txt"]}]}

    # messages = {
    #       "messages": [
    #       {
    #           "role": "user",
    #           "content": (
    #               "Translate the following sentence from English to Kannada.\n\n"
    #               f"English: {example['src_txt']}"
    #           ),
    #       },
    #       {
    #           "role": "assistant",
    #           "content": example["tgt_txt"],
    #       },
    #   ],
    # }


    return messages

# def format_example(example):
#     prompt = (
#         "Translate the following sentence from English to Kannada.\n\n"
#         f"English: {example['src_txt']}\n\n"
#         "Kannada:"
#     )

#     completion = " " + example["tgt_txt"]

#     return {
#         "prompt": prompt,
#         "completion": completion,
#     }

model_name = "google/gemma-3-270m-it"
# model_name = "ibm-granite/granite-4.0-h-350m"

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    use_fast=True,
)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

dataset_new = dataset['train'].map(
    format_example,
    num_proc=2,
    remove_columns=dataset['train'].column_names,
)
from trl import apply_chat_template
# dataset_new = dataset_new.map(
#         apply_chat_template,
#         fn_kwargs={
#             "tokenizer": tokenizer,
#         },
#         num_proc=4,
#         remove_columns=dataset_new.column_names,
#     )
print(dataset_new[0])

from trl.data_utils import is_conversational

print(is_conversational(dataset_new[0]))

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
)

sft_config = SFTConfig(
    output_dir="./gemma-en-kn",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=8,
    num_train_epochs=2,
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    logging_steps=50,
    bf16=True,
    max_length=8192,
    packing=False,
    report_to="none",
    completion_only_loss=True,
    # assistant_only_loss=True,
    # dataset_text_field="messages",
)

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset_new,
    peft_config=lora_config,
    args=sft_config,
    processing_class=tokenizer,
)

batch = next(iter(trainer.get_train_dataloader()))
input_ids = batch["input_ids"][0].cpu()
labels = batch["labels"][0].cpu()

tokens = tokenizer.convert_ids_to_tokens(input_ids)

print(tokens)
print(labels)
# for tok, lab in zip(tokens, labels.tolist()):
#     print(f"{tok}\t{lab}")

trainer.train()

import trl
print(trl.__version__)

