# -*- coding: utf-8 -*-
"""gemma FT 0_shot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZujHTbBeYJuxcWxKCdeU_MPzPXX2DsD
"""

!pip uninstall -y transformers tokenizers torchvision trl
!pip install -U \
    transformers==4.54.1 \
    tokenizers==0.21.1 \
    datasets==3.5.0 \
    sacrebleu==2.5.1 \
    torch==2.6.0 \
    torchvision==0.21.0 \
    tqdm==4.66.5 \
    peft==0.13.2 \
    bitsandbytes \
    accelerate
!pip install trl==0.25.0 #0.12.1

#!pip install git+https://github.com/Unbabel/COMET.git
!pip install evaluate

# ======================================================
# 🔐 Hugging Face Authentication
# ======================================================
from huggingface_hub import login

# Replace the token below with your actual HF access token
# (Get it from https://huggingface.co/settings/tokens)
login(token="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")

# ======================================================
# ✅ Universal Fine-tuning + Evaluation for Hugging Face instruct/causal LM
# (Streaming, LoRA, Fast Evaluation, Metrics, Top-10 Preview)
# Patched: Top-10 ASCII Table + Scores + Plots + JSONL + ZIP
# Refactored: Manual tokenization removed for training
# Safe tokenization filters applied to avoid empty prompts
# ======================================================

import os, json, zipfile, torch, random
from pathlib import Path
from datasets import load_dataset, get_dataset_split_names
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig, apply_chat_template
from tqdm import tqdm
import sacrebleu
from trl import apply_chat_template


# ------------------------------ CONFIG
MODEL_NAME = "google/gemma-3-270m-it"
OUTPUT_DIR = Path("./universal_output_best")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

MAX_SEQ_LEN = 1024
MAX_NEW_TOKENS = 256
BATCH_SIZE = 1
GRAD_ACCUM = 4
MAX_TRAIN_STEPS = 200
EVAL_BATCH_SIZE = 8
FULL_DATASET = False
MAX_COLAB_SAMPLES = 300

# ------------------------------ BEAM SWITCH
#BEAM_MODE = "A"  # "A" or "B"
#BEAM_KWARGS = dict(num_beams=5, num_return_sequences=1, early_stopping=True) if BEAM_MODE=="A" else dict(num_beams=5, length_penalty=1.0)

INDIAN_LANGS = ["hin","ben","tam","tel","mal","kan","mar","guj","urd","pan","ori"]
LANG_MAP = {
    "eng":"English","hin":"Hindi","ben":"Bengali","tam":"Tamil",
    "tel":"Telugu","mal":"Malayalam","kan":"Kannada","mar":"Marathi",
    "guj":"Gujarati","urd":"Urdu","pan":"Punjabi","ori":"Odia"
}

DIRECTIONS = ["eng_hin", "hin_eng"]  # dual-direction evaluation

# ------------------------------ MODEL PREP
def prepare_model():
    tok = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float32,
        device_map="auto"
    )

    try: model.gradient_checkpointing_enable()
    except: pass

    return model, tok

# ------------------------------ STREAM + TOKENIZE
def stream_examples_list(max_samples=None, tokenizer=None):
    dataset_name = "ai4bharat/Pralekha"
    config_name = "train"
    splits = get_dataset_split_names(dataset_name, config_name)
    split = splits[0]

    def build_prompt(example):
        prompt = f"Translate this {example['src_lang']} text to {example['tgt_lang']}:\n{example['src_txt']}"
        messages = {
            "messages": [
                {"role": "user", "content": prompt},
                {"role": "assistant", "content": example["tgt_txt"]}
            ],
        }
        return messages

    parts = split.split("_")
    sl, tl = parts
    lang = tl if sl=="eng" else sl

    dataset = load_dataset(dataset_name, split=split, streaming=True, name=config_name)
    print(dataset)

    if not FULL_DATASET and max_samples is not None:
        dataset = dataset.take(max_samples)

    dataset = dataset.map(build_prompt)
    dataset = dataset.map(apply_chat_template, fn_kwargs={"tokenizer": tokenizer})

    return dataset


# ------------------------------ TRAINING
def train_model(max_samples=None):
    model, tok = prepare_model()
    dataset = stream_examples_list(max_samples=max_samples, tokenizer=tok)

    peft_config = LoraConfig(r=16, lora_alpha=32, target_modules="all-linear")

    cfg = SFTConfig(
        output_dir=str(OUTPUT_DIR),
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRAD_ACCUM,
        learning_rate=1.5e-4,
        lr_scheduler_type="cosine",
        num_train_epochs=1,
        max_steps=MAX_TRAIN_STEPS,
        logging_steps=10,
        save_strategy="no",
        report_to="none",
        warmup_ratio=0.1,
        gradient_checkpointing=True,
        completion_only_loss=True,
        packing=False
    )

    assert cfg.max_steps is not None and cfg.max_steps > 0

    trainer = SFTTrainer(
        model=model,
        args=cfg,
        train_dataset=dataset,
        peft_config=peft_config,
    )

    trainer.train()
    return model, tok, trainer


# ---------------------------------------------------------
# FIXED: Chat-style tokenized prompt for evaluation
# STRICTLY identical to training prompt
# ---------------------------------------------------------
def build_eval_prompt_tokenized(example, tokenizer, src_lang, tgt_lang):
    user_prompt = f"Translate this {src_lang} text to {tgt_lang}:\n{example['src_txt']}"

    messages = [
        {"role": "user", "content": user_prompt},
        {"role": "assistant", "content": ""}
    ]

    input_ids = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=False
    )
    return input_ids


# ---------------------------------------------------------
# FIXED: Generate with variable-length slicing
# ---------------------------------------------------------
def generate_batch(model, tokenizer, batch_input_ids):
    enc = torch.nn.utils.rnn.pad_sequence(
        [torch.tensor(x) for x in batch_input_ids],
        batch_first=True,
        padding_value=tokenizer.pad_token_id,
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            enc,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False
        )

    results = []
    for i, ids in enumerate(batch_input_ids):
        prompt_len = len(ids)
        gen_ids = out[i][prompt_len:]
        text = tokenizer.decode(gen_ids, skip_special_tokens=True).strip()
        results.append(text)
    return results


# ---------------------------------------------------------
# FIXED: Single-split loader (ALWAYS load eng_hin)
# ---------------------------------------------------------
def load_pralekha_split(lang1, lang2):
    split = "eng_hin"
    print(f"Dataset load info: split='{split}'")
    return load_dataset(
        "ai4bharat/Pralekha",
        name="train",
        split=split,
        streaming=True
    )


# ---------------------------------------------------------
# FIXED: Correct evaluation for both eng→hin and hin→eng
# ---------------------------------------------------------
def evaluate_direction(model, tokenizer, src_lang, tgt_lang, max_samples=200, batch_size=8):
    ds = load_pralekha_split(src_lang, tgt_lang)
    ds_iter = iter(ds)

    preds, refs, srcs = [], [], []
    processed = 0

    pbar = tqdm(total=max_samples, desc=f"Evaluating {src_lang}→{tgt_lang}")

    while processed < max_samples:
        batch_src = []
        batch_refs = []
        batch_ids = []

        for _ in range(batch_size):
            try:
                ex = next(ds_iter)
            except StopIteration:
                break

            if src_lang == "eng" and tgt_lang == "hin":
                src_text = ex["src_txt"]
                ref_text = ex["tgt_txt"]
            else:
                src_text = ex["tgt_txt"]
                ref_text = ex["src_txt"]

            fake_ex = {"src_txt": src_text}
            ids = build_eval_prompt_tokenized(fake_ex, tokenizer, src_lang, tgt_lang)

            batch_src.append(src_text)
            batch_refs.append(ref_text)
            batch_ids.append(ids)

        if not batch_ids:
            break

        outs = generate_batch(model, tokenizer, batch_ids)

        preds.extend(outs)
        refs.extend([r.strip() for r in batch_refs])
        srcs.extend([s.strip() for s in batch_src])

        processed += len(batch_ids)
        pbar.update(len(batch_ids))

    pbar.close()
    print(f"Done: {processed} samples for {src_lang}→{tgt_lang}")

    bleu = sacrebleu.corpus_bleu(preds, [refs]).score
    chrf_metric = sacrebleu.metrics.CHRF(word_order=0)
    chrf = chrf_metric.corpus_score(preds, [refs]).score

    print(f"BLEU = {bleu:.2f}   chrF = {chrf:.3f}\n")
    return bleu, chrf


# ---------------------------------------------------------
# MAIN LOOP FOR BOTH DIRECTIONS
# ---------------------------------------------------------
if __name__ == "__main__":
    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

    max_samples = None if FULL_DATASET else MAX_COLAB_SAMPLES
    model, tokenizer, trainer = train_model(max_samples=max_samples)

    results = {}
    for split in DIRECTIONS:
        src, tgt = split.split("_")
        bleu, chrf = evaluate_direction(
            model, tokenizer, src, tgt,
            batch_size=EVAL_BATCH_SIZE
        )
        results[split] = {"BLEU": bleu, "chrF": chrf}

    print("\n✅ Final Results (ENG↔HIN):")
    for split, scores in results.items():
        print(f"{split}: BLEU={scores['BLEU']:.2f}, chrF={scores['chrF']:.3f}")

# --------------------- JSONL + ZIP --------------------------------------------
import json
import zipfile
from pathlib import Path
from google.colab import files

OUTPUT_DIR = Path("./universal_output_best")
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

directions = ["eng_hin", "hin_eng"]
max_samples = 150  # adjust as needed
batch_size = 8

# Save each direction as JSONL
jsonl_files = []
for split in directions:
    src, tgt = split.split("_")

    preds, refs = [], []
    ds = load_pralekha_split(src, tgt)
    ds_iter = iter(ds)
    processed = 0

    save_path = OUTPUT_DIR / f"{split}_pred_refs.jsonl"
    with open(save_path, "w", encoding="utf-8") as f:
        while processed < max_samples:
            batch_src, batch_refs, batch_ids = [], [], []

            for _ in range(batch_size):
                try:
                    ex = next(ds_iter)
                except StopIteration:
                    break

                if src == "eng" and tgt == "hin":
                    src_text = ex["src_txt"]
                    ref_text = ex["tgt_txt"]
                else:
                    src_text = ex["tgt_txt"]
                    ref_text = ex["src_txt"]

                fake_ex = {"src_txt": src_text}
                ids = build_eval_prompt_tokenized(fake_ex, tokenizer, src, tgt)

                batch_src.append(src_text)
                batch_refs.append(ref_text)
                batch_ids.append(ids)

            if not batch_ids:
                break

            outs = generate_batch(model, tokenizer, batch_ids)
            for p, r in zip(outs, batch_refs):
                json_line = json.dumps({"prediction": p, "reference": r}, ensure_ascii=False)
                f.write(json_line + "\n")

            processed += len(batch_ids)

    print(f"Saved {processed} examples to {save_path}")
    jsonl_files.append(save_path)

# Create ZIP of all JSONL files
zip_path = OUTPUT_DIR / "pred_refs_eng_hin.zip"
with zipfile.ZipFile(zip_path, 'w') as zipf:
    for jsonl_file in jsonl_files:
        zipf.write(jsonl_file, arcname=jsonl_file.name)

print(f"All JSONL files zipped at {zip_path}")

# Download the ZIP
files.download(str(zip_path))