# -*- coding: utf-8 -*-
"""Gemma-Eval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lErQdqeZEtJf8WnXZ350wIVJgmiuNiwe
"""

import os
import json
import torch
import numpy as np
import pandas as pd
import unicodedata
import matplotlib.pyplot as plt

from tqdm import tqdm
from pathlib import Path
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

# ============================================================
torch.manual_seed(42)
torch.cuda.manual_seed_all(42)

BASE_MODEL_ID = "google/gemma-3-270m-it"
DATASET_NAME = "ai4bharat/Pralekha"
EVAL_SPLIT = "test"
DEVICE = "cuda"

dataset = load_dataset(DATASET_NAME, EVAL_SPLIT, split="eng_hin")

from huggingface_hub import login
login("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")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
# tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL_ID,
    torch_dtype=torch.bfloat16 if torch.cuda.is_available() else torch.float32,
    device_map="auto",
    attn_implementation="sdpa",
)

model.eval()

def build_prompt(example):
  src = example["src_txt"]
  ref = example["tgt_txt"]

  prompt = (
      "Translate the following text from English to Hindi:\n"
      f"English: {src}\n"
      "Hindi: "
  )

  messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

  # Apply chat template
  prompt = tokenizer.apply_chat_template(
      messages,
      tokenize=False,
      add_generation_prompt=True,
  )

  tokens = tokenizer(
      prompt,
      truncation=True,
      padding=False,
  )

  return {
      "input_ids": tokens["input_ids"],
      "attention_mask": tokens["attention_mask"],
      "reference": ref,
  }


  return {"prompt": prompt, "reference": example["tgt_txt"]}


dataset = dataset.map(build_prompt)
print(dataset)

SRC_LANG = "eng"
TGT_LANG = "hin"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

BATCH_SIZE = 4
MAX_NEW_TOKENS = 2048

predictions = []
references = []

print("Running inference...")

for i in tqdm(range(0, len(dataset), BATCH_SIZE)):

    batch = dataset[i:i+BATCH_SIZE]

    padded = tokenizer.pad(
        {
            "input_ids": batch["input_ids"],
            "attention_mask": batch["attention_mask"],
        },
        padding=True,
        return_tensors="pt",
    )

    input_ids = padded["input_ids"].to(model.device)
    attention_mask = padded["attention_mask"].to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=MAX_NEW_TOKENS,
            do_sample=False,
            use_cache=True,
        )

    new_tokens = outputs[:, input_ids.shape[1]:]

    decoded = tokenizer.batch_decode(
        new_tokens,
        skip_special_tokens=True,
    )

    predictions.extend(decoded)

    refs = dataset[i:i+BATCH_SIZE]["reference"]
    references.extend(refs)

